.gitleaks.toml
Now that we are public we need to include this file to remove the false positives we know should not trigger the security flag.
If you have gitleaks installed you should be able to run this command from our root directory to see no issues:
```
gitleaks -v --additional-config .gitleaks.toml --path ./
```
=> Add .gitleaks.toml to remove false positives from scan

pinakes/main/approval/serializers.py, pinakes/main/approval/tests/functional/test_request_end_points.py
Implements https://issues.redhat.com/browse/SSP-2825.
Groups assigned to a request can be useful to distinguish requests.
=> Expose group_name in request apis

pinakes/main/common/tasks.py, pinakes/settings/defaults.py
Since we use session based authentication there are times when
a user might not logout and leave a session dangling. These sessions
have to be cleared according to Django documentation.
This PR clears out stale sessions everyday at midnight
=> Clear expired sessions

tools/minikube/scripts/start_pods.sh
If the env_vars is missing the script doesn't exist, it creates
an incomplete env which needs to be cleaned up.
If we leave the set -o nounset and the env var is missing the error
generated is not user friendly
./tools/minikube/scripts/start_pods.sh: line 11: PINAKES_CONTROLLER_URL: unbound variable
=> Fix start_pods script when env vars are missing

docs/MINIKUBE.md, overrides/.gitignore, tools/minikube/scripts/server.sh, tools/minikube/scripts/start_pods.sh
If an end user wants to put custom images and css they can do
that by providing files in the overrides directory.
The UI tar file goes into
* ./overrides/ui/catalog-ui.tar.gz
The CSS/images can be stored in
* ./overrides/pinakes
* ./overrides/approval
* ./overrides/keycloak
=> Support overriding images/css and UI.tar

docs/MINIKUBE.md
Is it a typo that the path has two `tmp`? In my minikube there is only one `tmp` in the path.
=> Fix path of the temp folder that stores the PV

tools/docker/docker-compose.stage.yml, tools/docker/scripts/keycloak-setup.sh, tools/keycloak_setup/dev.yml
Fix variable name for keycloak setup. Upgrade version of keycloak setup collection. add ssl for keycloak and configure variable to use tls internally and externally in docker-compose stage environment
It's the same PR as #405 due to conflicts with the old ansible-catalog fork
=> add https for keycloak in docker-compose stage

docs/MINIKUBE.md, tools/minikube/scripts/start_pods.sh
For minikube environments,
When the user calls start_pods.sh if the image is not present
the script will build the image. It saves a manual step for
the user.
=> Ease of use, build the image for the user if not present

pinakes/main/auth/urls.py
We were missing the query_string setting when calling  the redirect.
This was preventing the next query parameter from getting passed to
the redirect
https://issues.redhat.com/browse/SSP-2849
https://docs.djangoproject.com/en/4.0/ref/class-based-views/base/#django.views.generic.base.RedirectView.query_string
=> [SSP-2849] Pass query_string to redirect

pinakes/common/auth/keycloak_oidc.py, pinakes/settings/defaults.py
During social auth login, when Keycloak returns HTTP error in response
to a back channel request it is hard to determine actual error reason,
because response body is not logged.
This PR fixes the problem by logging HTTP response error details.
Example:
```
[2022-04-07 16:02:10,412] [59066] [ERROR] pinakes keycloak_oidc 139865600587328 HTTPError: POST http://localhost:8080/auth/realms/pinakes/protocol/openid-connect/token 401 Unauthorized [unauthorized_client] Invalid client secret
```
=> Log social auth http error detail

tools/keycloak_setup/collection/roles/setup/vars/catalog_rbac.yml
For admin resources their permission should be expilictly set to
e.g. catalog:portfolios:all
Previously this used to use resourceType: catalog:portfolios
This was first uncovered during Approval Testing
https://issues.redhat.com/browse/SSP-2839
=> [SSP-2839] Fix keycloak permission for admin resources

pinakes/data/email_template.html, pinakes/main/approval/models.py, pinakes/main/approval/services/create_request.py, pinakes/main/approval/services/email_notification.py, pinakes/main/approval/tests/services/test_email_notification.py, pinakes/main/approval/urls.py, pinakes/main/catalog/services/submit_approval_request.py, pinakes/main/catalog/views.py
https://issues.redhat.com/browse/SSP-2842
https://issues.redhat.com/browse/SSP-2799
https://issues.redhat.com/browse/SSP-2610
Read the html email template and replace with runtime parameters. Fetch members of an approver group. Send customized email per approver.
Initially use the email template from the cloud version. Will need some modifications in a future PR.
Will need another PR to handle certificates for SSL connection to SMTP server.
Will need to decide what to send for plain email.
=> [SSP-2842]Add service class for sending email

README.md, docs/CONTRIBUTING.md
Added a link to our new ansible-pinakes gitter channel to the README and CONTRIBUTING docs. Will also update the wiki.
=> Add gitter info to readme and contribution docs

pinakes/main/migrations/0040_seed_email_notification_type.py
The migration fails in minikube deployment if the MEDIA_ROOT folder does not exist.
=> Create MEDIA_ROOT folder if not exists

pinakes/main/approval/services/email_notification.py, pinakes/main/approval/services/update_request.py, pinakes/main/approval/tests/services/test_email_notification.py, pinakes/main/approval/tests/services/test_update_request.py, pinakes/main/approval/validations.py
https://issues.redhat.com/browse/SSP-2843
Send email notifications during the approval request processing. It is backward compatible. System will auto-notify if no email settings are configured.
Re-enable previously skipped tests due to lacking of notification.
=> [SSP-2843] Enable email notification

pinakes/main/inventory/services/start_tower_job.py, pinakes/main/inventory/tests/services/test_start_tower_job.py
An incorrect API endpoint for launching workflow job templates is used, which causes orders for products based on workflow templates to fail.
This patch corrects that and updates the tests to suit.
=> Use correct workflow job templates API endpoint.

pinakes/main/inventory/task_utils/service_offering_import.py, pinakes/main/inventory/tests/task_utils/test_service_offering_import.py
Fix refresh error when service offering's related inventory is none.
```
[2022-04-18 20:58:36,289] [212] [ERROR] refresh_inventory 140240078336256 Refresh failed: expected string or bytes-like object
[2022-04-18 20:58:36,317] [212] [ERROR] refresh_inventory 140240078336256 Traceback (most recent call last):
File "/opt/app-root/src/pinakes/main/inventory/task_utils/refresh_inventory.py", line 64, in process
soi.process()
File "/opt/app-root/src/pinakes/main/inventory/task_utils/service_offering_import.py", line 56, in process
self._process_job_templates()
File "/opt/app-root/src/pinakes/main/inventory/task_utils/service_offering_import.py", line 100, in _process_job_templates
self._handle_obj(new_obj, OfferingKind.JOB_TEMPLATE)
File …
```
=> Fix service offering with none related inventory

pinakes/main/inventory/task_utils/service_inventory_import.py, pinakes/main/inventory/task_utils/service_offering_import.py
Fix KeyError by logging a warning message in `source_ref_to_id` function:
```
[2022-04-18 22:51:12,788] [176] [ERROR] refresh_inventory 139922874429696 Refresh failed: 10
[2022-04-18 22:51:12,789] [176] [ERROR] refresh_inventory 139922874429696 Traceback (most recent call last):
File "/opt/app-root/src/pinakes/main/inventory/task_utils/refresh_inventory.py", line 70, in process
son.process()
File "/opt/app-root/src/pinakes/main/inventory/task_utils/service_offering_node_import.py", line 42, in process
self._process_workflow_job_template_nodes()
File "/opt/app-root/src/pinakes/main/inventory/task_utils/service_offering_node_import.py", line 79, in _process_workflow_job_template_nodes
self._handle_obj(new_obj)
File "/opt/app-root/src/pinakes/main/inventory/task_utils/service_offering_node_im …
```
=> Fix KeyError in source_ref_to_id function

docs/DOCKER_COMPOSE.md, tools/docker/frontend/Dockerfile
- Allow overrides the UI's tar file at frontend image build time for docker-compose based environments
- Add documentation
- Standardize docs format.
=> allow override UI's build tarfile for docker-compose

tools/docker/frontend/Dockerfile
Fix #484
Always download the artifact otherwise the layer can not be updated properly and fix copy task.
=> Fix override task for docker-compose

pinakes/main/catalog/exceptions.py, pinakes/main/catalog/services/cancel_order.py, pinakes/main/catalog/tests/functional/test_order_end_points.py, pinakes/main/catalog/tests/services/test_cancel_order.py, pinakes/main/catalog/views.py
Add the endpoint `/orders/:id/cancel` to cancel the order
https://issues.redhat.com/browse/SSP-2885
=> [SSP-2885] Add endpoint to cancel the order

pinakes/main/auth/tests/functional/test_session_logout.py, pinakes/main/auth/views.py
The exception is caused by `get_serializer()` method override,
returning None.
Removing the override doesn't affect OpenAPI schema generation.
https://issues.redhat.com/browse/SSP-2879
=> [SSP-2879] Fix DRF browser for SessionLogoutView

pinakes/main/catalog/views.py
https://issues.redhat.com/browse/SSP-2894
Allow for Portfolio searches to include  user's 
* first_name
* last_name
* username
=> [SSP-2894] Added user first name & last name to searchable fields

pinakes/common/auth/keycloak_django/permissions.py, pinakes/common/auth/keycloak_django/tests/test_permission_base_class.py, pinakes/common/auth/keycloak_django/views.py, pinakes/common/fields.py, pinakes/main/approval/permissions.py, pinakes/main/approval/views.py, pinakes/main/catalog/serializers.py, pinakes/main/catalog/tests/functional/test_order_end_points.py, pinakes/main/catalog/tests/functional/test_order_item_end_points.py, pinakes/main/catalog/tests/functional/test_portfolio_end_points.py, pinakes/main/catalog/tests/functional/test_portfolio_item_end_points.py, pinakes/main/catalog/views.py
Implement basic user capabilities support.
* Add UserCapabilitiesField class, a serializer field that
returns user capabilities mapping.
* Implement `user_capabilities()` method in base permission class.
* Use `keycloak_permission` view attribute to indicate keycloak
permission class explicitely, which is required for generating user
capabilities mapping out of permission class.
* Update existing view sets to reflect changes in view's permission
classes definition.
NOTE: This is the first of a series PRs that introduce user capabilities support. Caching will be introduced in subsequent PR.
https://issues.redhat.com/browse/SSP-2807
=> [SSP-2807] User capabilities basic implementation

pinakes/common/fields.py, pinakes/main/catalog/serializers.py
* Use field instead of serializer to generate instance metadata and use
appropriate OpenAPI type annotation.
* Add default value for compatibility with original metadata OpenAPI
schema.
* Allow overriding nested user capabilities field.
https://issues.redhat.com/browse/SSP-2902
=> [SSP-2902] Fix OpenAPI schema generation for metadata field

pinakes/common/auth/keycloak_django/permissions.py, pinakes/common/auth/keycloak_django/tests/test_permission_checks.py, pinakes/main/approval/permissions.py, pinakes/main/catalog/permissions.py
Reduce code duplication by passing request object to the permission
helper functions:
- check_wildcard_permission
- check_object_permission
- get_permitted_resources
=> Refactoring: Pass request object to permission helper functions

pinakes/data/email_template.html, pinakes/main/approval/services/email_notification.py
Add the following phrase to the email body: `You received this email because you are a member of group ...`. This is helpful to explain if why an approver receives multiple email notifications if he happens to belong to two groups.
=> Add group_name to the email content

pinakes/main/approval/services/email_notification.py, pinakes/main/approval/tests/services/test_email_notification.py
https://issues.redhat.com/browse/SSP-2895
The user provide key and certificate are stored in database. The smtp library requires them to be files.
=> [SSP-2895] Save client key and certificate in temp files

pinakes/settings/defaults.py
if a new en var PINAKES_REDIS_UNIX_SOCKET_PATH is defined
store it as UNIX_SOCKET_PATH for redis settings
https://issues.redhat.com/browse/SSP-2911
=> [SSP-2911] Support UNIX_SOCKET_PATH for Redis

pinakes/settings/defaults.py
Cherry-pick over #496 to the stable branch
=> [Stable] [SSP-2911] Support UNIX_SOCKET_PATH for Redis

pinakes/main/inventory/task_utils/launch_job.py, pinakes/main/inventory/tests/task_utils/test_launch_job.py
When a job doesn't have successful status we were not raising
an error.
https://issues.redhat.com/browse/SSP-2901
=> [SSP-2901] Failed jobs were not raising exception

pinakes/main/catalog/models.py, pinakes/main/catalog/permissions.py, pinakes/main/catalog/tests/functional/test_progress_message_end_points.py, pinakes/main/catalog/tests/unit/test_progress_message_permissions.py, pinakes/main/catalog/urls.py, pinakes/main/catalog/views.py
Implement a permission class for `ProgressMessage` viewset.
Issue: https://issues.redhat.com/browse/SSP-2765
=> [SSP-2675] Add progress message permission

pinakes/main/catalog/models.py, pinakes/main/migrations/0046_progressmessage_nullable_fields.py
The `messageable_type` and `messageable_id` are not expected to
contain `NULL` value. This patch makes those fields non-nullable.
=> Misc: Make ProgressMessage model fields non nullable

docs/CREDENTIALS.md, docs/RBAC.md, tools/keycloak_setup/collection/roles/setup/vars/catalog_rbac.yml, tools/keycloak_setup/dev.yml
The approval-user is some thing that we brought over from the
cloud version when the services were separate and we needed a
default role for Approval service. Now that we are on premise
we don't have separate services so we dont need the approval-user
role
=> Removed the approval-user role

pinakes/main/catalog/permissions.py, pinakes/main/catalog/services/copy_portfolio.py, pinakes/main/catalog/services/copy_portfolio_item.py, pinakes/main/catalog/tests/functional/test_portfolio_item_end_points.py, pinakes/main/catalog/tests/services/test_copy_portfolio_item.py, pinakes/main/catalog/views.py
Copy of a portfolio now checks `read` permission on source portfolio
item and `update` permission on target portfolio.
Issue: https://issues.redhat.com/browse/SSP-2855
=> [SSP-2855] Fix permission check on PortfolioItem copy

docs/LOCAL_DEV.md
The markdown was missing  the backticks
=> Fixed typo in doc

docs/DOCKER_COMPOSE.md, tools/docker/docker-compose.stage.yml, tools/docker/scripts/keycloak-setup.sh, tools/keycloak_setup/qa.yml
- Add the ability to override the users and groups seeded by keycloak setup. 
- Fix a bug where we were running the command twice. 
- Add a new file with an extended set of users and groups. This is required by the QA team to cover more cases for RBAC testing.
=> Override users/groups and add QA seed file

conftest.py, lint-requirements.txt, pinakes/main/analytics/tests/test_analytics_collectors.py, pinakes/main/approval/services/process_root_request.py, pinakes/main/approval/validations.py, pinakes/main/catalog/services/create_portfolio_item.py, pinakes/main/common/tasks.py
A `flake8` plugin that helps you writing better list/set/dict comprehensions.
For the list of warnings see https://github.com/adamchainz/flake8-comprehensions#rules
Example: `./pinakes/main/common/tasks.py:110:27:`
```
existing_role_names = set(role.name for role in obj.roles.all())
^
```
Example: `./pinakes/main/catalog/services/create_portfolio_item.py:90:13:`
```
set([field.name for field in PortfolioItem._meta.get_fields()])
^
```
Example: `./conftest.py:48:18`
```
defaults=dict(is_superuser=False, password="normal"),
^
```
Example: `./pinakes/main/analytics/tests/test_analytics_collectors.py:104:21:`
```
lines = [line for line in reader]
^
```
Example `./pinakes/main/approval/services/process_root_request.py:74:30:`
```
all_names = ",".join(map(lambda x: x["group_name"], sub_groups)) …
```
=> Lint: Add flake8-comprehensions plugin

pinakes/main/migrations/0030_create_email_template.py, pinakes/main/migrations/0031_create_default_source.py
Migrations must not depend on actual models, since any change
to a dependant model can potentially break migrations.
=> Fix migrations dependency on actual model

pinakes/common/auth/keycloak/client.py, pinakes/common/auth/keycloak/exceptions.py, pinakes/common/auth/keycloak/tests/unit/test_client.py, pinakes/common/auth/keycloak/tests/unit/test_uma_client.py, pinakes/common/auth/keycloak/uma.py
* Add docstrings.
* Rename `ApiException` to `HttpError` class.
* Consistent naming for `NoResultFound` and `MultipleResultsFound`
exceptions.
* Use dispatch dictionary to return a concrete `HttpError` child class.
=> Refactor error handling in keycloak client

pinakes/main/inventory/serializers.py, pinakes/main/inventory/task_utils/refresh_inventory.py, pinakes/main/inventory/tests/functional/test_source_endpoints.py
The refresh message was missing the service plan counters
https://issues.redhat.com/browse/SSP-2981
Before
After
=> [SSP-2981] Last refresh messages was not reporting on survey updates

pinakes/common/exception_handler.py
Return 403 status code when backend uses expired access token
to access Keycloak.
https://issues.redhat.com/browse/SSP-2946
=> [SSP-2946] Exception handler for Keycloak Unauthorized

pinakes/main/analytics/analytics_collectors.py, pinakes/main/analytics/tests/test_analytics_collectors.py
During analytics collections, some orders may still in the pending state and theirs `completed_at` is not set yet. Fix to return empty string in this case, instead of isoformat conversion.
https://issues.redhat.com/browse/SSP-2984
=> [SSP-2984] Fix calling isoformat on null completed_at in analytics collectors

pinakes/main/analytics/analytics_collectors.py, pinakes/main/analytics/tests/test_analytics_collectors.py
Approval request may have no `notified_at` timestamp, even when it already finished. Fix analytic collector to use `created_at` for this case.
https://issues.redhat.com/browse/SSP-2984
=> [SSP-2984] Fix empty notified_at even when request has finished_at

pinakes/main/approval/services/update_request.py, pinakes/main/approval/tests/services/test_process_root_request.py, pinakes/main/approval/tests/services/test_update_request.py
https://issues.redhat.com/browse/SSP-3004
When a group is included in two workflows we will auto approve the second workflow. This PR fixes a bug that continues to start the email notification the second time while the request is already auto approved. 
Also rename two private methods to be more meaingful.
=> [SSP-3004] Conditionally skip external notification

pinakes/main/catalog/tests/functional/test_order_end_points.py, pinakes/main/catalog/urls.py
Remove `delete` and `patch` actions from the endpoint of `orders/:id`
https://issues.redhat.com/browse/SSP-3002
=> [SSP-3002] Remove extra actions from the orders/:id endpoint

pinakes/main/catalog/serializers.py
Add the missing `nullable` for `request_completed_at` of approval request
https://issues.redhat.com/browse/SSP-3018
=> [SSP-3018] Add missing nullable for request_completed_at

pinakes/main/approval/services/process_root_request.py
https://issues.redhat.com/browse/SSP-3004
Fixed the second issue reported in above issue. When we select sub-requests to start they must belong to the same parent. Otherwise older finished requests might be selected that result in the error `InvalidStateTransitionException`
=> [SSP-3004] Select sub-requests belong to the same parent only

pinakes/settings/defaults.py
At the moment when `DEBUG=True`, SQL queries are unconditionally logged,
which produces noise in server log output. This change adds an environment
variable `PINAKES_DEBUG_SQL` that if set overrides SQL debug log level.
=> Misc: Make SQL debug log configurable

pinakes/settings/defaults.py
Pinakes uses only Keycloak authentication backend.
The `ModelBackend` enables username \ password authentication,
which is not used in the project.
It was only unappropriately used in the unit tests, which got
replaced in #562.
=> Misc: Remove unused ModelBackend

tools/keycloak_setup/collection/roles/setup/defaults/main.yml, tools/keycloak_setup/collection/roles/setup/tasks/create_cli_client.yml, tools/keycloak_setup/collection/roles/setup/tasks/main.yml, tools/keycloak_setup/dev.yml, tools/keycloak_setup/qa.yml
Add new keycloak client `pinakes-cli` for development environment
to issue standalone access tokens for external applications.
Issue: https://issues.redhat.com/browse/SSP-2819
Related: #562
=> [SSP-2819] New Keycloak client for Bearer auth

conftest.py, docs/AUTHENTICATION.md, pinakes/common/auth/keycloak_django/authentication.py, pinakes/common/auth/keycloak_django/permissions.py, pinakes/common/auth/keycloak_django/test_authentication_backends.py, pinakes/main/auth/serializers.py, pinakes/main/auth/tests/functional/test_session_logout.py, pinakes/main/auth/views.py, pinakes/settings/defaults.py
* Add `KeycloakBearerOfflineAuthentication` authentication class.
It implements offline access token validation, by verifying token
signature. Enabled by default.
* Add `KeycloakBearerOnlineAuthentication` authentication class.
It implements online access token authentication by calling Keycloak's
`introspect` endpoint to validate token itself and `userinfo` endpoint
to fetch user details.
* Add `KeycloakSessionAuthentication` class for an appropriate
integration of middleware with DRF authentication infrastructure.
Implements: https://issues.redhat.com/browse/SSP-2818
=> [SSP-2818] Bearer token authentication

setup.cfg
The wrong filename can prevent the dist pkg build. 
please @eclarizio review.
=> fix license filename
