ansible/pinakes

- .github/workflows/python-package.yml
- pinakes/common/image_mixin.py
- pinakes/common/nested_router.py
- pinakes/main/approval/permissions.py
- pinakes/main/catalog/tests/functional/test_order_end_points.py
- pinakes/main/catalog/views.py
- pinakes/settings/development.py
- setup.cfg
- tox.ini
* Fix flake8 issues.
* Make flake8 mandatory in GitHub Actions.
* Move flake8 settings from `tox.ini` to `setup.cfg`
> Fix flake8 issues, enable CI check

- pinakes/main/approval/views.py
- pinakes/main/common/views.py
https://issues.redhat.com/browse/SSP-2815
Add role query parameter for groups. Fix the similar problem for workflows filtered by a resource object.
> Add explicitly query params for groups and workflows openapi.json

- pinakes/main/common/tests/functional/test_groups.py
- pinakes/main/common/views.py
It helps to restore the search capability
https://issues.redhat.com/browse/SSP-2814
> Use GroupFilterBackend to filter groups by roles

- tools/docker/Dockerfile
- tools/docker/docker-compose.override.yml
- tools/docker/docker-compose.stage.yml
- tools/docker/scripts/dev-server.sh
- tools/docker/scripts/keycloak-setup.sh
- tools/docker/scripts/server.sh
- tools/docker/scripts/worker.sh
Update docker-compose environments for better control of container startup.
Now Keycloak setup uses an control file and a chain of dependencies is implemented:
keycloak -> keycloak-setup -> app -> worker
With this change we fix some errors due to a wrong order.
> improve startup control in docker-compose

- .github/workflows/python-package.yml
- README.md
- test-requirements.txt
Support code coverage using python-cov and upload to codecov
> Codecov support

- .github/workflows/python-package.yml
If any or our dependencies change this scheduled pytest run every 12 hours will catch
errors. Based on
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
> Run pytest twice a day

- pinakes/main/inventory/task_utils/tower_api.py
- pinakes/main/inventory/tests/task_utils/test_tower_api.py
The strtobool returns 1/0 not a boolean.
Fixes #441
The verify_ssl can be one of these True|False|CA cert file
Also related to
https://issues.redhat.com/browse/SSP-2787
> Incorrect use of strtobool

- pinakes/main/inventory/task_utils/service_plan_import.py
There was a bug  introduced in PR https://github.com/ansible/pinakes/pull/461
Checking for empty string and None was off
> [SSP-2854] Wasn't importing survey specs

- conftest.py
- pinakes/common/auth/keycloak/tests/unit/test_admin_client.py
- pinakes/main/auth/tests/functional/test_me_endpoint.py
- pinakes/main/catalog/services/finish_order.py
- pinakes/main/migrations/0040_seed_email_notification_type.py
- pinakes/settings/defaults.py
> [Stable] Update stable

- pinakes/main/inventory/task_utils/refresh_inventory.py
Add more error details when refresh fails with tower queries.
> Add traceback when refresh fails

- docs/LOCAL_DEV.md
Add instructions to run localization step by step
> Add details in the doc for running localization

- pinakes/common/auth/keycloak_django/permissions.py
- pinakes/common/auth/keycloak_django/tests/test_permission_base_class.py
- pinakes/common/auth/keycloak_django/views.py
- pinakes/common/fields.py
- pinakes/main/approval/permissions.py
- pinakes/main/approval/views.py
- pinakes/main/catalog/serializers.py
- pinakes/main/catalog/tests/functional/test_order_end_points.py
- pinakes/main/catalog/tests/functional/test_order_item_end_points.py
- pinakes/main/catalog/tests/functional/test_portfolio_end_points.py
- pinakes/main/catalog/tests/functional/test_portfolio_item_end_points.py
- pinakes/main/catalog/views.py
Cherry-picking #481 and #491 to the stable branch.
> [Stable] [SSP-2807] [SSP-2902] Cherry pick user capabilities

- docs/MINIKUBE.md
Documents how to reclaim space and delete image
> Add cleanup notes for minikube

- pinakes/main/migrations/0047_rename_default_template.py
https://issues.redhat.com/browse/SSP-2914
Update the title and description of the default template to reflect more accurately the use of the template.
> [SSP-2914] Rename default template

- pinakes/main/analytics/collector.py
- pinakes/main/analytics/package.py
- pinakes/settings/defaults.py
- tools/minikube/scripts/start_pods.sh
- tools/minikube/templates/app-deployment.yaml
- tools/minikube/templates/scheduler-deployment.yaml
- tools/minikube/templates/worker-deployment.yaml
Add support to authenticate with user id and password when connect to ingress service.
https://issues.redhat.com/browse/SSP-2913
> [SSP-2913] Add credential support to ingress service for metrics collection

- docs/CREDENTIALS.md
- docs/RBAC.md
- tools/keycloak_setup/collection/roles/setup/vars/catalog_rbac.yml
- tools/keycloak_setup/dev.yml
This PR pulls in #514 to the stable/1.0 branch.
> [Stable] Removed the approval-user role

- pinakes/main/analytics/analytics_collectors.py
- pinakes/main/analytics/tests/test_analytics_collectors.py
https://issues.redhat.com/browse/SSP-2940
> [SSP-2940] Add missing tower information to the config json in metrics collection

- docs/MINIKUBE.md
Formatting and typos fixes in `MINIKUBE.md`.
> Misc: Improve docs

- pinakes/main/migrations/0050_remove_notificationtype_main_notificationtype_n_type_unique_and_more.py
Resolve conflicting migrations:
* `0049_notificationsetting_encryption`
* `0049_remove_notificationtype_main_notificationtype_n_type_unique_and_more`
> [SSP-2954] Fix migrations conflict

- pinakes/main/analytics/analytics_collectors.py
- pinakes/main/analytics/tests/test_analytics_collectors.py
Changed the key name to follow the snake case convention
https://issues.redhat.com/browse/SSP-2324
> [SSP-2324] Fix key to snake case

- tools/docker/docker-compose.stage.yml
- tools/docker/docker-compose.yml
Add mailcatcher in docker-compose envs for easy debugging of mail notifications
> add mailcatcher for docker-compose envs

- pinakes/main/catalog/services/validate_order_item.py
Fixed a Survey Spec reset message.
https://issues.redhat.com/browse/SSP-2996
> [SSP-2996] Fixed a survey reset message

- pinakes/main/approval/serializers.py
- pinakes/main/approval/tests/functional/test_request_end_points.py
- pinakes/main/approval/views.py
https://issues.redhat.com/browse/SSP-2745
Disable the creation by user directly.
> [SSP-2745] Remove Request API create endpoint

- pinakes/main/analytics/collector.py
- requirements.txt
Update insights-analytics-collector to 0.2.0
It better handles saving of last gathered entries
https://issues.redhat.com/browse/AA-1319
> Update saving in analytics collector

- tools/docker/scripts/keycloak-setup.sh
Fixes https://github.com/ansible/pinakes/issues/584
> Fix keycloak-setup pinning the version of community-general collection

- tools/docker/scripts/keycloak-setup.sh
@Alex-Izquierdo @ttuffin I just cherry-picked this commit, let me know if I should instead just create a merge PR where we bring all of devel into stable/1.0.
> [Stable] Backport #585 (Fix keycloak-setup) to stable/1.0
